### ISSUE TITLE
request returns 401

### ISSUE THREAD

**Issue by akshaysahu121** [mdesilva/AmazonFlexUnlimited#10]
while running the script it returns ERROR: Unable to authenticate to Amazon Flex. Please provide a valid Amazon Flex username and password. and the request returns 401 unauth 
tried with multiple account but stays the same.  ./sh file returns null

**Comment by theramzaan** [comment]
We trying India is there change required for county 
@mdesilva  please contact @ theramzaan@yahoo.com truly need your help to complete this and  it would be pleasure to work with you 
Waiting for you mail
