### ISSUE TITLE
Reserved block, duration time, incorrect format!

### ISSUE THREAD

**Issue by ransel2016** [mdesilva/AmazonFlexUnlimited#105]
It only happens to me when it is a reserved block, normal block has no problem

Date: 28/03
Pay: $72
Duration: 20.411111111111 hours
Start time: 04:00 AM
End time: 08:00 AM

**Comment by ademircan** [comment]
I had the similar issue and this change helped me.

Find this in offer.py
`self.expirationDate = datetime.fromtimestamp(offerResponseObject.get("expirationDate"))`

Change to this:
`self.expirationDate = datetime.fromtimestamp(offerResponseObject.get("startTime"))`

**Comment by possiblemeatball** [comment]
I have created a pull request to properly fix this issue for all. Thank you!
