### ISSUE TITLE
I can't get the highest blocks, yet the other bots are faster Is there anything I can do to make it better?

### ISSUE THREAD

**Issue by Hrasseee** [mdesilva/AmazonFlexUnlimited#109]

**Comment by ssmusic19** [comment]
@Hrasseee you can get a cheap AWS server, put this script on there, and it'll have much lower latency, low as 0.5ms ping.
You can check your current ping in your terminal, ping flex-capacity-na.amazon.com

**Comment by ssmusic19** [comment]
Also, rejecting blocks from stations/times you don't want will increase the speed that it takes to receive a request from the offers route.

**Comment by Hrasseee** [comment]
Thank you for your answer, do you have any to indicate me?  I tried that but it showed several errors

https://www.pythonanywhere.com/user/Reps/account/#email

**Comment by ssmusic19** [comment]
https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all

**Comment by ransel2016** [comment]
> [https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free% 20Tier%20Categorías=*todas](https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all)

ssmusic19:

I have been trying to automate the process of arriving at the store and passing the selfie, what have you been able to see about this, I would appreciate your help. Regards

**Comment by ssmusic19** [comment]
@ransel2016 I don't know. Please don't hijack other issue's threads to ask me an unrelated question. If I had an answer for you, I would've answered you in the issue you created.

**Comment by ransel2016** [comment]
> @ransel2016 I don't know. Please don't hijack other issue's threads to ask me an unrelated question. If I had an answer for you, I would've answered you in the issue you created.

Thanks for taking the time to reply, sorry for posting out of context. Greetings

**Comment by Hrasseee** [comment]
The servers that I found most are Amazon's AWS, do you think it's okay for me to put or script there?
