### ISSUE TITLE
Script ends in 3 seconds after starting

### ISSUE THREAD

**Issue by N3N-X** [mdesilva/AmazonFlexUnlimited#137]
Message:
***Amazon Flex Unlimited v2*** 

INFO: Starting job search...
0 requests attempted

INFO: Job search cycle ending...
INFO: Accepted 0 offers in 3.523017168045044 seconds

**Comment by cpietrobelli** [comment]
I think that if you don't know about computers or have a little knowledge of how a script works, you are putting your Amazon account at risk.

You need to edit the retryLimit
