### ISSUE TITLE
Using 'filters: serviceAreaFilter' doesn't affect the result in any way.

### ISSUE THREAD

**Issue by hoqua** [mdesilva/AmazonFlexUnlimited#156]
I tried to work on optimizing bot's response-request, and I investigated `filters`. It seems that in the `GetOffersForProviderPost` request body:

```
  {
    apiVersion: 'V2',
    filters: {
      serviceAreaFilter,
      timeFilter: { startTime, endTime }
    },
    serviceAreaIds
}
```

It doesn't matter what you pass in `serviceAreaFilter`; it simply has no effect on the response. Is that correct, or is it some kind of mistake on my part?

**Comment by jaimbox** [comment]
> I tried to work on optimizing bot's response-request, and I investigated `filters`. It seems that in the `GetOffersForProviderPost` request body:
> 
> ```
>   {
>     apiVersion: 'V2',
>     filters: {
>       serviceAreaFilter,
>       timeFilter: { startTime, endTime }
>     },
>     serviceAreaIds
> }
> ```
> 
> It doesn't matter what you pass in `serviceAreaFilter`; it simply has no effect on the response. Is that correct, or is it some kind of mistake on my part?

When you send any serviceAreaId through serviceAreaFilter only the 'hidden' field is modified.

**Comment by hoqua** [comment]
@jaimbox  thanks for clarifying that!
