### ISSUE TITLE
Help with proxy needed: Forfeiting Offer Feature

### ISSUE THREAD

**Issue by hoqua** [mdesilva/AmazonFlexUnlimited#164]
Hi all! I want to implement the `Forfeiting Offer Feature`

For this purpose, I attempted to investigate Amazon Flex requests. However, my data is encrypted.

I am using Charles Proxy, and here are my results:
<img width="1202" alt="image" src="https://github.com/mdesilva/AmazonFlexUnlimited/assets/11320835/27452bf1-3a59-4868-8795-a5c658643fdb">

Does anyone know how to set it up properly to decrypt the requests?

**Comment by lazyniuk** [comment]
You should to add ssl certificates
https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/
