### ISSUE TITLE
btw i made it work in semiauto mode. basically run flex mod app + python code on the same ubuntu box. I changed flex smali code to dump signatures to emulator shared folder so python can grab it. Its a quite messy way but kinda works.

### ISSUE THREAD

**Issue by asadbek064** [mdesilva/AmazonFlexUnlimited#165]
"we launched technology to confirm that a mobile phone using the Amazon Flex app is accessing our backend systems." By running the app and Python code together should mask the request signature. Great idea I'll test it out.

**Comment by asadbek064** [comment]
.

**Comment by asadbek064** [comment]
**Behavioral Analysis**
Analyzing the usage patterns and behaviors of a device, such as location data, frequency of use, or consistency of access times, can help identify abnormal or bot-like activity.
So to not trigger detection it is vital that the (real) mobile app with the vps app and python code should run under one proxy IP. 

That is easy to implement but there is another flaw in this. The (real) mobile and the vps app will end up generating two different tokens idk if they are checking for that also but that is another thing to test for. If this is the case then the only way to make it work is to not use the (real) app while the vps app is running thus not triggering detection.

**Comment by MY20-PHEV** [comment]
> **Behavioral Analysis**
> Analyzing the usage patterns and behaviors of a device, such as location data, frequency of use, or consistency of access times, can help identify abnormal or bot-like activity.
> So to not trigger detection it is vital that the (real) mobile app and the terminal app and code should run under one proxy IP.

This is not really true in this case, mobile apps are continually getting new IP's every time they drive by a new cell tower. Im running with a different ip for the bot and whatever the flex app gets from a cell connection without detection.
