### ISSUE TITLE
Error 410

### ISSUE THREAD

**Issue by alexxd35** [mdesilva/AmazonFlexUnlimited#169]
I have made extensive changes and optimizations to the script, especially in the part after getOfferList where processOffer is called. However, I still encounter 410 errors. Although there are instances of success, about 8 out of 10 attempts result in a 410 error. I am wondering if triggering the 410 error could be related to grabbing offers too quickly.(I know that requesting too slowly can lead to a 410 error, but is it also possible that requesting too quickly might trigger it, causing the server to block the requests?)

**Comment by juanc2503** [comment]
How did you bypass the error 420 about the signatures? I believe there should be a trigger also where the accept cant be too fast also.

**Comment by sierraxdev** [comment]
@alexxd35 Have you been able to fix the 410 errors?

**Comment by HNBR** [comment]
> @alexxd35 Have you been able to fix the 410 errors?

I don't think that sharing any progress publicly in this repo is good at all if it's not foolish, please be careful discussing any breakthroughs here.

**Comment by sierraxdev** [comment]
@HNBR you are right, I'm glad I could fix it. Thanks.
