### ISSUE TITLE
Twilio Issue - ERROR: 'twilioAcctSid' was not set. Please setup FlexUnlimited as described in the README.

### ISSUE THREAD

**Issue by ususus1987** [mdesilva/AmazonFlexUnlimited#19]
I have added the following values in the Config and I keep seeing this issue

C:\Users\mohan\Desktop\AmazonFlexUnlimited-master>python app.py
***Amazon Flex Unlimited v2***

ERROR: 'twilioAcctSid' was not set. Please setup FlexUnlimited as described in the README.

I also tried it without Twilio's values since the they mentioned it is an optional feature and still does not work.
Any help ???

**Comment by figamore** [comment]
Apparently the value twilioAccountSID is misspelled in the config.json gile, change it to twilioAccountSid instead

**Comment by ususus1987** [comment]
I did that and I had the same issue.
I solved it by replacing the Twilio's Values in the FlexUnlimited.py file
