### ISSUE TITLE
FILTER NOT WORKING!!!

### ISSUE THREAD

**Issue by ususus1987** [mdesilva/AmazonFlexUnlimited#22]
I have tried changing the DesiredWarehouses and it is still accepting any offer show up
any assistance please!

**Comment by mdesilva** [comment]
What did you change `desiredWarehouses` to ? Please post a code snippet here.

**Comment by ususus1987** [comment]
I used the following in config.json and it is accepting any offer comes up and the filter is not working:
["5d91901f-19ac-4619-b167-961a54f5de0c", "2f819ba4-8c85-45a9-abda-3b7e5d11fdad", "501517e9-6135-4902-9621-ebe5dc895bdf", "22eaac51-fa93-4d4f-8847-2db4a02181d2", "88c3e32b-7c01-4510-88bf-7f43b5d175eb"]

**Comment by mdesilva** [comment]
Hi @ususus1987, please pull the latest code and try again. I implemented a different way of filtering the locations. Let me know if the filter works now.
