### ISSUE TITLE
QUESTION: "serviceAreaIds" ???

### ISSUE THREAD

**Issue by ususus1987** [mdesilva/AmazonFlexUnlimited#24]
Do I need to find my "serviceAreaIds" value and replace it with one exist in FlexUnlimited.py ??? or should I leave as it is ["2"] ???

**Comment by mdesilva** [comment]
You don't need to modify anything in **FlexUnllimited.py**. The only file you need to modify is **config.json** in the root directory with your preferences. Here, `desiredWarehouses` represents a list of warehouses you want to restrict your search to, if any. If you don't want to restrict it, just leave it as an empty list. Amazon should only return results limited to your area anyway.

**Comment by ususus1987** [comment]
so in the beginning, when I run the app, it was searching but I was not finding anything.
Then, I was looking inside the FlexUnlimited.py and I found the "serviceAreaIds" in line 141 was as the following:
"serviceAreaIds": ["2"],

Then, after I used Charles Proxy to sniff the service area IDs of my Amazon Flex app, I found the serviceAreaId is different than the one exist in FlexUnlimited.py

Here is my Charles Proxy results:
{
	"apiVersion": "V2",
	"filters": {
		"timeFilter": {
			"endTime": "23:00",
			"startTime": "00:00"
		},
		"deliveryRequestFilter": {
			"orderCount": 0,
			"deliveryRequestCount": 0
		},
		"serviceAreaFilter": ["5d91901f-19ac-4619-b167-961a54f5de0c", "2f819ba4-8c85-45a9-abda-3b7e5d11fdad", "501517e9-6135-4902-9621-ebe5dc895bdf", "22eaac51-fa93-4d4f-8847-2db4a02181d2", "88c3e32b-7c01-4510-88bf-7f43b5d175eb"]
	},
	"serviceAreaIds": ["48aa0c62-def7-4bef-8fbb-b53424739946"]
}

------------
so after I changed the serviceAreaIds to the one above, your app started to pickup any Amazon blocks and it is not filtering anything.

FYI, I used the 5 service IDs in the config.json.

**Comment by ususus1987** [comment]
So I am main working area is Greater Los Angles which is represented by:
["48aa0c62-def7-4bef-8fbb-b53424739946"]

and the station that wanted to filter are:
["5d91901f-19ac-4619-b167-961a54f5de0c", "2f819ba4-8c85-45a9-abda-3b7e5d11fdad", "501517e9-6135-4902-9621-ebe5dc895bdf", "22eaac51-fa93-4d4f-8847-2db4a02181d2", "88c3e32b-7c01-4510-88bf-7f43b5d175eb"]

**Comment by mdesilva** [comment]
@ususus1987 With the latest version of the code you shouldn't need to manually enter your `serviceAreaIds`. This will be filled in automatically for you with your eligible `serviceAreaIds`. Please pull the latest code and try again. As for the filter, I am still working on that.

**Comment by Xande1** [comment]
> @ususus1987 With the latest version of the code you shouldn't need to manually enter your `serviceAreaIds`. This will be filled in automatically for you with your eligible `serviceAreaIds`. Please pull the latest code and try again. As for the filter, I am still working on that.

First of all, thanks Manuja for all of your work and support. And everyone else's contribution building a stronger community to keep this project alive. This might be the case for skipping offers:

self.minBlockRate:
      if self.minBlockRate > offer.blockRate:
        return

self.minBlockRate should be < than offer.blockRate to be rejected.

**Comment by ususus1987** [comment]
@mdesilva Thanks.
I noticed that which is great but I still have the filter issue. It is accepting from any warehouse

**Comment by ususus1987** [comment]
@Xande1
I will check and update you here

**Comment by mdesilva** [comment]
@Xande1 Good catch on the `minBlockRate` condition. I've patched that and also set `minBlockRate` to 0 as default (so by default all blocks meet the `minBlockRate` condition)

**Comment by ususus1987** [comment]
**IT IS WORKING NOW** :)

But i suggest to change the following in the READ ME file:
For Windows: pip install -r requirements to pip install -r requirements.txt
For Mac OS: pip3 install -r requirements to pip3 install -r requirements.txt

Desired Warehouses: [2,acf06702-57ba-47f3-a34f-19e536a69fc0] to ["2","acf06702-57ba-47f3-a34f-19e536a69fc0"]

**Comment by mdesilva** [comment]
I've corrected the typos on the readme. I've left `desiredWarehouses` as `[]` so that users don't restrict their search to warehouses  that are not necessarily part of their area.
