### ISSUE TITLE
Random Authentication issue.

### ISSUE THREAD

**Issue by Xande1** [mdesilva/AmazonFlexUnlimited#25]
Are you guys  experiencing the same? I randomly receive this error while running the script. Sometimes after a few requests attempt, some time it takes longer to show up.

250 requests attempted
300 requests attempted
ERROR: {'Message': 'before - AuthorizationRequiredException validating token with Aztec; x-amz-access-token: Atna|EwICIPWdH0sPt7VDVbh1Hq9Ubi2CjT6LIBWJCbHcMymqLmSaSqfstcn1QWiekfgkYKQyBRxwPdAY4WFfD8LXMnXOeXNxVTzGFmOqT_iNE-1aJjj-GyTZnkgnsgISWXZ9v8dejlqgu4a9ocVDVLsFicmFkyZaqh1HViN6p7zeWHitx3mwUuA5u2Q0kF2W8X0p7K1go68lZCbq4ro4ohJLg7RjOZpO8PvDqcWXIANWNJCkIfR22g, requestId: 987deb7d-0089-4825-9e72-3e0008bf1f3c'}
INFO: Job search cycle ending...
INFO: Accepted 0 offers in 384.28913044929504 seconds

**Comment by Xande1** [comment]
can't reproduce

**Comment by guaguadiwa** [comment]
Yes, I have the same issue. No idea what happened.
