### ISSUE TITLE
Unable to accept an offer. Request returned status code 410

### ISSUE THREAD

**Issue by ususus1987** [mdesilva/AmazonFlexUnlimited#27]
What does it mean when:

Unable to accept an offer. Request returned status code 410

![Screenshot 2022-09-14 205150](https://user-images.githubusercontent.com/93367390/190309913-dce26883-963c-4391-85c9-49e3192fe777.png)

**Comment by Xande1** [comment]
410 error code means gone. Offer is no longer available.

**Comment by ususus1987** [comment]
Thanks
