### ISSUE TITLE
Hosting on AWS for minimum latency

### ISSUE THREAD

**Issue by figamore** [mdesilva/AmazonFlexUnlimited#28]
Hello, 

I know the readme says that the bot did not work on AWS, but that is not the case, as many other bots use AWS. I just tested the latency to flex-capacity-na from my AWS server and it is only 0.9ms, compared to an average of 33ms in my 1Gbps/1Gbps residential connection. I'm wondering if this will create an issue long term? Has anybody tried running the script on AWS for an extended time?

**Comment by han-jt** [comment]
I tried it on aws a month ago. It worked fine, but i havent tried it now. As for the latency on my aws server i was getting around 0.2-0.3ms but still it was missing the blocks, thats why i dont use it anymore. Also did you use the ping command to the flex? Because ping only sends 64 bytes to the flex server, as for the post request its size is usually around 30 to 50 kilobytes. So, still you will not be able to achieve that latency.

**Comment by ususus1987** [comment]
I just tried it on AWS EC2, running Ubuntu Server and I ran it and it was working great on California server.
Then, I found that their server is located in Virginia, So I made another server in Virginia and I was able to 500 request in 62 sec.
The latency was 0.5ms which is ideal, but guess what, I missed another offer and the error shown was 410.
Can you believe that?

**Comment by han-jt** [comment]
Use the request.elapsed on the request in the accept offer function. It will show you how long the post request took from Amazon server to your server. Then let me know, I used to get around 0.8 to 0.20s. I might help you with that

**Comment by figamore** [comment]
> I just tried it on AWS EC2, running Ubuntu Server and I ran it and it was working great on California server.
> 
> Then, I found that their server is located in Virginia, So I made another server in Virginia and I was able to 500 request in 62 sec.
> 
> The latency was 0.5ms which is ideal, but guess what, I missed another offer and the error shown was 410.
> 
> Can you believe that?
> 
> 

You're going WAYY too fast and may get banned. Try putting a 3-5 second delay between each request.

**Comment by ususus1987** [comment]
> > I just tried it on AWS EC2, running Ubuntu Server and I ran it and it was working great on California server.
> > Then, I found that their server is located in Virginia, So I made another server in Virginia and I was able to 500 request in 62 sec.
> > The latency was 0.5ms which is ideal, but guess what, I missed another offer and the error shown was 410.
> > Can you believe that?
> 
> You're going WAYY too fast and may get banned. Try putting a 3-5 second delay between each request.

I was thing thinking about that, Thanks.
Would you please tell me how to do it please?

**Comment by ususus1987** [comment]
> Use the request.elapsed on the request in the accept offer function. It will show you how long the post request took from Amazon server to your server. Then let me know, I used to get around 0.8 to 0.20s. I might help you with that

Thanks, Im not a Python Expert, but I understand the language.
if you can just let me know how to do it so, I can get back to you with results

**Comment by han-jt** [comment]
Replace this line
return requests.post(FlexUnlimited.routes.get("GetOffers"), headers=self.__requestHeaders,  json=requestBody)

with this line
request = requests.post(FlexUnlimited.routes.get("GetOffers"), headers=self.__requestHeaders, json=requestBody)
print(request.elapsed.total_seconds())
return request

**Comment by ususus1987** [comment]
The second worked
The first one did not work!!!
in your first comment, you mentioned "Use the request.elapsed on the request in the accept offer function"
the you sent me is in the GetOffer function.

**Comment by han-jt** [comment]
my bad It is getOffer function.

**Comment by Ahdrumond** [comment]
> I just tried it on AWS EC2, running Ubuntu Server and I ran it and it was working great on California server. Then, I found that their server is located in Virginia, So I made another server in Virginia and I was able to 500 request in 62 sec. The latency was 0.5ms which is ideal, but guess what, I missed another offer and the error shown was 410. Can you believe that?

Hi!
Is there any chance you could tell me where to find a toturial on how to do this. I have the code running on my machine perfectly but I would like to see how it behaves on a virtual server.

thanks
