### ISSUE TITLE
please tell me why it says Unable to authenticate

### ISSUE THREAD

**Issue by santiagoyamamoto** [mdesilva/AmazonFlexUnlimited#29]
I tried to do what you said
But your program said that something like this.
***Amazon Flex Unlimited v2***
ERROR: Unable to authenticate to Amazon Flex. Please provide a valid Amazon Flex username and password.

please solve this problem

**Comment by ususus1987** [comment]
to solve this problem temporarily, open up Microsoft Edge and go to Amazon.com then sign in using your Amazon Flex Account.
Then try your account.

**Comment by santiagoyamamoto** [comment]
I have done like this.
I used account which I have in Amazon.com
But still I noticed that It is unable to authenticate
please fix this problem

**Comment by ususus1987** [comment]
try this way:
make sure your Phone (Amazon Flex App) and the computer are connected to the same home WiFi then, Log out & Sign In again on Amazon Flex App in your phone then, run the script on your computer. It worked with me

Im not the developer of this App, the developer is still working on it and he is done a great job with his project.
try to visit this project from time to time to see if he did any changes.

Thanks....

**Comment by mdesilva** [comment]
I'm still trying to replicate this issue in order to provide a fix for it. Once I do I will update this thread.

**Comment by santiagoyamamoto** [comment]
in auth part.
I wanted to know why it can't authorize.
So I put exception in console
it is like this.
this is response:
{'response': {'challenge': {'challenge_reason': 'HandleOnWebView', 'uri': '
https://www.amazon.com/ap/challenge?arb=16a2242f-5ead-430b-b6ac-8628a5fb896c'}},
'request_id': 'b76d5c43-47e2-4f19-ae63-b6e5d9c17a37'}
this is exception:
ERROR: 'NoneType' object has no attribute 'get'

In my opinion , error occurs in       return response.get("response").get(
"success").get("tokens").get("bearer").get("access_token")
what about your opinion

**Comment by sneezyxl** [comment]
@santiagoyamamoto I can help you get setup with the program if you want to.

Just going to ask the basic first. 
1. Were you able to open the config.json file to add your username and password into the json format 
"username": "example@gmail.com",
  "password": "Enter your password",
  
2. Do you happen to have the application download mitmproxy
I used this app to gather my device serial and gather the FRC. 
(im using an iphone )
-    Once you download mitmproxy open up terminal 
- type "ipconfig" and write down your ipv4 address
- type "mitmproxy" it will show flow at the top of terminal that how you will now its running. 
- on the iphone navigate to Setting>Wifi>tap the i for more information about the wifi you're connected. scroll down to find http proxy tap on Configure proxy>manual>Server will be your ipv4 address > port will be 8080 then hit save on the top right.

3.navigate to amazon flex app sign out and sign back in

-you will see on the terminal under flow amazon get request 
-Look for the POST /auth/register scroll down and gather the serial and the frc 
-after you had copy the information you will have to enter the info into the flexunlimited.py file

i hope it helps if not reach out. This is currently how im able to get logged in.

**Comment by santiagoyamamoto** [comment]
I did all my work in my computer.
you mean I can login when I use mitmproxy?.
If so , could you explain about it in more detail.
If it is possible please give me video attachment about how to do it.
Thank you for your kind.

**Comment by mdesilva** [comment]
Please pull the latest code and try again. I have updated the app to account for the two step verification process that needs to be done when logging in. Let me know how it goes.

**Comment by bessaoudi** [comment]
hi,
i had the same probleme, i changed password and username in auth.sh with mines, it work well now.

**Comment by mike503** [comment]
Did not work for me as of the latest as of right now. Even tried doing it on same connection as my phone in case it has some sort of IP checking or persistence, any of that. no matter what, can't get it to auth.

command line (with personal info changed)

```
$ python app.py 
***Amazon Flex Unlimited v2*** 

Unable to authenticate to Amazon Flex.

Please try completing the two step verification challenge at https://www.amazon.com/ap/challenge?openid.return_to=https://www.amazon.com/ap/maplanding&openid.oa2.code_challenge_method=XXX&openid.assoc_handle=amzn_device_ios_us&pageId=amzn_device_ios_light&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:1234&language=en_US&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.code_challenge=sdfsdfasdfas-423423423423&openid.oa2.scope=device_auth_access&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.response_type=code&arb=uuid-1234-4567-4234 . Then try again.

If you already completed the two step verification, please check your Amazon Flex username and password in the config file and try again.
```

I load the URL in my browser, login and nit sends me to:

![image](https://user-images.githubusercontent.com/301652/199641826-1a59f64f-4a0b-4878-916c-75b230a65865.png)

**Comment by mike503** [comment]
when using the curl example in lib/auth.sh (replacing my own information) I get this response. no idea if it's an outdated method or not.

loading that URI even with a fake user agent returns a 404. (changed the uuids for privacy)

```
{
  "response": {
    "challenge": {
      "challenge_reason": "HandleOnWebView",
      "uri": "https://www.amazon.com/ap/challenge?arb=432423-f8ba-9283-f9d3-819287d73f"
    }
  },
  "request_id": "298d18bc8-aaaa-bbbb-cccc-ddddddddd"
}
```

**Comment by mdesilva** [comment]
> Did not work for me as of the latest as of right now. Even tried doing it on same connection as my phone in case it has some sort of IP checking or persistence, any of that. no matter what, can't get it to auth.
> 
> command line (with personal info changed)
> 
> $ python app.py _**Amazon Flex Unlimited v2**_
> 
> Unable to authenticate to Amazon Flex.
> 
> Please try completing the two step verification challenge at https://www.amazon.com/ap/challenge?openid.return_to=https://www.amazon.com/ap/maplanding&openid.oa2.code_challenge_method=XXX&openid.assoc_handle=amzn_device_ios_us&pageId=amzn_device_ios_light&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:1234&language=en_US&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.code_challenge=sdfsdfasdfas-423423423423&openid.oa2.scope=device_auth_access&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.response_type=code&arb=uuid-1234-4567-4234 . Then try again.
> 
> If you already completed the two step verification, please check your Amazon Flex username and password in the config file and try again.
> 
> I load the URL in my browser, login and it sends me to:
> 
> ![image](https://user-images.githubusercontent.com/301652/199641826-1a59f64f-4a0b-4878-916c-75b230a65865.png)

You are supposed to get the "Looking for something?" page after you login. Once you get that page, re-run `app.py` and it should work.

**Comment by mike503** [comment]
> You are supposed to get the "Looking for something?" page after you login. Once you get that page, re-run `app.py` and it should work.

I could have sworn I tried that (and I did) - I just tried it again, no dice.

Should this be using Safari on the phone, Chrome on the desktop, indifferent? I've tried the links on both. All I get is another link to try again, looks like the "arb" param changes, at least.

**Comment by mdesilva** [comment]
The browser you use shouldn't make a difference. You might have to try several times before the login succeeds. Logging out and logging in on your device might also help. In the meantime I'll work on a more foolproof way of logging in.

**Comment by mike503** [comment]
FWIW, I've logged out, in, tried to reauth over and over, it never wound up working
