### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Alexrapo87** [mdesilva/AmazonFlexUnlimited#30]
Hello, first I want to thank you for this valuable tool. I have been trying to run the application for a long time and I have had several errors that I have been correcting little by little, I have very little programming knowledge and it is difficult for me to solve these errors. I was finally able to run it but two seconds later it stops. There is something that needs to be modified or changed. The Windows firewall and antivirus have already been disabled and the problem is not resolved.
INFO: Starting job search...
0 requests attempted

INFO: Job search cycle ending...
INFO: Accepted 0 offers in 2.943331003189087 seconds

**Comment by Ahdrumond** [comment]
yo need set the "retryLimit" on config.json.

**Comment by mdesilva** [comment]
Can you post a full trace of the results after executing the program ?

**Comment by Alexrapo87** [comment]
> Can you post a full trace of the results after executing the program ?


INFO: Starting job search...
0 requests attempted


50 requests attempted


ERROR: {'message': 'Rate exceeded'}
INFO: Job search cycle ending...
INFO: Accepted 0 offers in 11.762121677398682 seconds
PS C:\Users\Alejandro\Desktop\Flex\AmazonFlexUnlimited-master>

**Comment by Alexrapo87** [comment]
> You need set the "retryLimit" on config.json.

the "retryLimit" is 800

**Comment by mdesilva** [comment]
Do you get this error all the time or once in a while ? Usually the "Rate exceeded" error means that you've temporarily exceeded the number of job searches you can do.
