### ISSUE TITLE
Not able to log in

### ISSUE THREAD

**Issue by cristibokos2000** [mdesilva/AmazonFlexUnlimited#31]
ERROR: Unable to authenticate to Amazon Flex. Please provide a valid Amazon Flex username and password.
I am getting an OTP on my mobile number when I run the app.py

**Comment by mdesilva** [comment]
Please try again. I have updated the app to account for the two step verification process that needs to be done when logging in. Let me know how it goes.

**Comment by cristibokos2000** [comment]
Unable to authenticate to Amazon Flex.

Please try completing the two step verification challenge at https://www.amazon.com/ap/challenge?openid.return_to=https://www.amazon.com/ap/maplanding&openid.oa2.code_challenge_method=S256&openid.assoc_handle=amzn_device_ios_us&pageId=amzn_device_ios_light&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:30324244334531423246314134354635394236443142424234413744443936452341334e5748585451344542435a53&language=en_US&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.code_challenge=n76GtDRiGSvq-Bhrez9x0CypsZFB_7eLfEDy_qZtqFk&openid.oa2.scope=device_auth_access&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.response_type=code&arb=09320621-2169-4476-83d0-d4e834e4ca1d . Then try again.

If you already completed the two step verification, please check your Amazon Flex username and password in the config file and try again.

**Comment by ususus1987** [comment]
> Please pull the latest code and try again. I have updated the app to account for the two step verification process that needs to be done when logging in. Let me know how it goes.

I have the same issue
and sometimes I am able to solve it by opening amazon.com on a browser and sign in with the same amazon flex account and I have get the captcha 
Then, I am able to search for jobs

I already pulled the latest code and tried it

**Comment by cristibokos2000** [comment]
Do you know why I get this error then? No module named 'lib'

**Comment by mdesilva** [comment]
Are you running python3 ? You can verify by running `python --version`. If you get a version below 3, try running `python3 --version`. If this fails, then you need to install python3. Then follow the instructions in the readme again.
