### ISSUE TITLE
searching specific warehouses

### ISSUE THREAD

**Issue by bessaoudi** [mdesilva/AmazonFlexUnlimited#33]
hi,
i'm trying to select specific warehouses, i live in san fransisco bay area, you wrote on the discription "For warehouses not in the table above, you'll have to snoop on requests made by the Amazon Flex app to get the internal warehouse id" i would like more information on how to find internals warehouses in my region.
thank you.

**Comment by mdesilva** [comment]
Good point. I will create a feature to make it easier to choose the warehouses you want.

**Comment by bessaoudi** [comment]
thank you so much,
i m waiting your update

**Comment by bessaoudi** [comment]
hi, did you find some time for this topic?
thank you.

**Comment by bessaoudi** [comment]
i found some internal ids : " apparently method is simple: you have just to print(offers.location) in FlexUnlimited.py 
    # internal id of richmond warehouse (DSF8) is : a3340e09-90db-4b46-b60a-42d3c6c3dd3e
    # internal id of oakland warehouse (DSJ9) is : a8d7ad0d-abe4-4e8c-a157-d07170c2f929
    # internal id of richmond ca warehouse (VCA3) is : 04577cb2-cbf4-4b7a-bac9-62253e8ee34e
    # internal id of oakland ca warehouse (DSJ9) is : 01d12a4f-d594-4cfe-8319-9c4be14bf027

**Comment by samkhazi** [comment]
Hi 
I'm facing issue routing for India please guide me

**Comment by mdesilva** [comment]
@bessaoudi @samkhazi I've added the ability to get a list of all the warehouses you are eligible for. Pull the latest code and refer to the updated readme.

**Comment by bessaoudi** [comment]
thank you so much
