### ISSUE TITLE
Can't be authenticated after put correct username and password

### ISSUE THREAD

**Issue by guaguadiwa** [mdesilva/AmazonFlexUnlimited#35]
The endpoint I'm hitting is 
https://api.amazon.com/auth/register

However, the response I get is following:

```json
{
    "response": {
        "challenge": {
            "challenge_reason": "HandleOnWebView",
            "uri": "https://www.amazon.com/ap/challenge?arb=03609690-02dd-4f27-97ad-b1c67f4dv776"
        }
    },
    "request_id": "c0001606-206a-4641-a1a4-300b60c09765"
}
```

This means that the authentication process has failed. And then normally I have to wait for 2 hours and try again and it will work for a couple of times and then it will repeat this again and again
@mdesilva Do you know what does this mean and is there a way that we can avoid this? Thanks!

**Comment by mdesilva** [comment]
You shouldn't need to hit that endpoint manually. Running the program using the provided instructions should allow you to login without doing any further work yourself.

**Comment by mdesilva** [comment]
Follow the troubleshooting steps in the readme if you are still having trouble.
