### ISSUE TITLE
Route issue

### ISSUE THREAD

**Issue by samkhazi** [mdesilva/AmazonFlexUnlimited#37]
Hi
I'm facing issue routing for India please guide me

**Comment by Winthan** [comment]
you are going to end up with account lockup.

**Comment by samkhazi** [comment]
> you are going to end up with account lockup. 

How can I setup automatic ( every day I need to login my flex account once it's connected ) after I get looking for something

**Comment by mdesilva** [comment]
You can setup a cronjob to run this automatically. See https://en.wikipedia.org/wiki/Cron
