### ISSUE TITLE
Used the auth after the login at https://www.amazon.com/ap/maplanding?captcha_verified=1

### ISSUE THREAD

**Issue by Winthan** [mdesilva/AmazonFlexUnlimited#38]
After captcha verification, you will get all the codes that you may need for header requests.  With that URL along can fix all the routing and account lockdown, rather than using a username/password. Can we do that?

**Comment by mdesilva** [comment]
What codes are you referring to? Where do you see them ? It might be possible to use that for credentials rather than using username and password.

**Comment by cristibokos2000** [comment]
I think he is talking about the link you get after you enter the two-factor authentication code

**Comment by Winthan** [comment]
If you are using 

Try to see the return of the URL code after login. And you don't need to request every time for {'serviceAreaIds'}, you could have saved it in memory and used it rather than hitting the amazon server for requesting to know serviceAreaIds.

`https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&use_global_authentication=false&captchaObfuscationLevel=ape:ZWFzeQ==&accountStatusPolicy=P1&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&language=en_US&pageId=amzn_device_ios_light&alertCodes=PLEASE_ENTER_PASSWORD_CAPTCHA&openid.return_to=https://www.amazon.com/ap/maplanding&forceCaptcha=true&openid.assoc_handle=amzn_device_ios_us&openid.oa2.response_type=token&openid.mode=checkid_setup&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.scope=device_auth_access&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.oa2.client_id=device:32663430323338643639356262653236326265346136356131376439616135392341314d50534c4643374c3541464b&openid.ns=http://specs.openid.net/auth/2.0`



`https://www.amazon.com/ap/challenge?openid.return_to=https://www.amazon.com/ap/maplanding&openid.oa2.code_challenge_method=S256&openid.assoc_handle=amzn_device_ios_us&pageId=amzn_device_ios_light&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:30324244334531423246314134354635394236443142424234413744443936452341334e5748585451344542435a53&language=en_US&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.code_challenge=n76GtDRiGSvq-Bhrez9x0CypsZFB_7eLfEDy_qZtqFk&openid.oa2.scope=device_auth_access&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.response_type=code&arb=3ebe753c-9d6a-4a9b-b686-439bbe7d5a6c`

All you need is a header request to pull the offers, right? You will not need username/password to do so. 

```

'x-amz-access-token': 'Atna|XXX', 

'Authorization': 'RABBIT3-HMAC-SHA256 SignedHeaders=x-amz-access-token;x-amz-date, 
Signature=82e65bd06035d5XXX3ac9c48559c52c7574XXXXX', 

'X-Amz-Date': '202211XXXXZ', 
'Accept-Encoding': 'gzip, deflate, br', 
'x-flex-instance-id': 'BEEXXXX3-47C5-B1D2-21507C831580', 

'Accept-Language': 'en-US', 'Content-Type': 'application/json', 'User-Agent': 'iOS/15.2 (iPhone Darwin) Model/iPhone Platform/iPhone13,3 RabbitiOS/2.88.2', 
'Connection': 'keep-alive', 

'Cookie': 'session-id=147-740XXX90-69XX8; session-id-time=208XX01l; session-token=XXXXXPxwNhA4uwXXXm; at-main="Atza|XXXXX"; sess-at-main="XXXfM="; ubid-main=131-1001797-1551209; x-main="ur180BSwQksvu@cBWHXXXXVZWlh15tnxZdlXXqO0"'
```
