### ISSUE TITLE
Filtering Offers

### ISSUE THREAD

**Issue by han-jt** [mdesilva/AmazonFlexUnlimited#42]
Hi
Is it possible that the server filters our offers depending on the warehouse? Because right now the script first receives all the offers from the server and then filters the offers. Is it possible that I write my warehouse id in the post request and the server only sends me offers for that specific warehouse.
Thanks

**Comment by mdesilva** [comment]
No, the filtering of offers is not done server side. I also wondered about this when I first wrote the app.
