### ISSUE TITLE
Refresh Tokens 

### ISSUE THREAD

**Issue by samkhazi** [mdesilva/AmazonFlexUnlimited#48]
Hey, 
      I just made a bot for block brabber. But all the tokens which I am using are getting expired after every one hour.So yesterday I was looking for a solution, then I came to know that instead of access token, we have to use refresh tokens. But i don't know from where and how to get refresh tokens. 
    Please help me on this issue

**Comment by cristibokos2000** [comment]
I am having the same problem

**Comment by samkhazi** [comment]
Let me know if u get any solution

**Comment by cristibokos2000** [comment]
All the bots that are running are taking all the information from the link you get after you enter the OTP in the webpage

**Comment by ssmusic19** [comment]
Here's some code to get the refresh token assuming you have the resulting maplanding URL after logging in using your Amazon username and password.
https://gist.github.com/ssmusic19/6c35aa92d71d6020d60dcaa296c5d7d3

**Comment by ssmusic19** [comment]
I should add that I'm using this URL:
https://www.amazon.com/ap/signin?ie=UTF8&clientContext=134-9172090-0857541&openid.pape.max_auth_age=0&use_global_authentication=false&accountStatusPolicy=P1&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&use_audio_captcha=false&language=en_US&pageId=amzn_device_na&arb=97b4a0fe-13b8-45fd-b405-ae94b0fec45b&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.assoc_handle=amzn_device_na&openid.oa2.response_type=token&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&disableLoginPrepopulate=0&openid.oa2.client_id=device%3A32663430323338643639356262653236326265346136356131376439616135392341314d50534c4643374c3541464b&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0"
to generate the maplanding URL that my code above parses. I did this manually in a browser, but once you get the refresh token you're set.

**Comment by samkhazi** [comment]
Can we get Access token by that map landing URL ???

**Comment by ssmusic19** [comment]
Basically you just go to the link I added above, sign in, then copy that resulting URL and use it in the register function. That function returns both a refresh token and an access token. You can then use the refresh token to request new access tokens when your access tokens expire. You have to save this refresh token somewhere. I added a third function in the code I shared to demonstrate requesting a new access token.

**Comment by samkhazi** [comment]
Thank you so much brother

**Comment by samkhazi** [comment]
@ssmusic19 how can we implement " I Have Arrived " feature ???

**Comment by ssmusic19** [comment]
@samkhazi I don't know :/

**Comment by samkhazi** [comment]
@ssmusic19 can u help me on arrival timing in filter

**Comment by ssmusic19** [comment]
@samkhazi with what about it exactly?

**Comment by samkhazi** [comment]
If I want to do Jo at between 1pm-4pm then bot should pick blocks between that time only

**Comment by samkhazi** [comment]
I want 30 minutes to reach station from my location then bot shout accept block before 30 minutes to start the block

**Comment by ssmusic19** [comment]
In the config.json file, set the arrivalBuffer to 30

**Comment by ssmusic19** [comment]
In my pull request, I used minutes as units. In the original, it's in hours.
