### ISSUE TITLE
continuing running

### ISSUE THREAD

**Issue by Jevus09** [mdesilva/AmazonFlexUnlimited#50]
Is there a way to let the program running? When I start the program and set the "retryLimit" in the config file, higher than 100, I receive the message

"ERROR: {'Message': 'before - AuthorizationRequiredException validating token with Aztec; x-amz-access-token"

When I set it to 100, it runs for only about 40 - 60 seconds and then it stops. Any help would be appreciated.

**Comment by KNelTech** [comment]
Hey guys did this work to loop the script over 100? I was also thinking to just run it from bash like every 10 seconds. Not sure dont wanna screw this up. any advice helps =]

**Comment by travislazzaro** [comment]
anyone know how to get the script to search continuously? it stops after one attempt

**Comment by russbakr** [comment]
im sure there is a better way but i edited the config.json and it looks like this

"retryLimit": 10000000,

**Comment by dymmyttry** [comment]
Does anyone know the parameters to leave running 24 hours in 10 seconds?

**Comment by Jevus09** [comment]
> Does anyone know the parameters to leave running 24 hours in 10 seconds?

five seconds worked perfect for me. Left it all day and it never stopped.
