### ISSUE TITLE
Amazon.co.jp

### ISSUE THREAD

**Issue by dymmyttry** [mdesilva/AmazonFlexUnlimited#51]
can anybody help me

i work in japan. How to change parameters to connect to amazon.co.jp

**Comment by ademircan** [comment]
I work in Australia but we also use jp domain. This worked for me.

```
routes = {
        "GetOffers": "https://flex-capacity-jp.amazon.com/GetOffersForProviderPost",
        "AcceptOffer": "https://flex-capacity-jp.amazon.com/AcceptOffer",
        "GetAuthToken": "https://api.amazon.com/auth/register",
        "ForfeitOffer": "https://flex-capacity-jp.amazon.com/schedule/blocks/",
        "GetEligibleServiceAreas": "https://flex-capacity-jp.amazon.com/eligibleServiceAreas",
        "GetOfferFiltersOptions": "https://flex-capacity-jp.amazon.com/getOfferFiltersOptions"
    }
```

**Comment by dymmyttry** [comment]
> I work in Australia but we also use jp domain. This worked for me.
> 
> ```
> routes = {
>         "GetOffers": "https://flex-capacity-jp.amazon.com/GetOffersForProviderPost",
>         "AcceptOffer": "https://flex-capacity-jp.amazon.com/AcceptOffer",
>         "GetAuthToken": "https://api.amazon.com/auth/register",
>         "ForfeitOffer": "https://flex-capacity-jp.amazon.com/schedule/blocks/",
>         "GetEligibleServiceAreas": "https://flex-capacity-jp.amazon.com/eligibleServiceAreas",
>         "GetOfferFiltersOptions": "https://flex-capacity-jp.amazon.com/getOfferFiltersOptions"
>     }
> ```

thank you very much. I'm still having difficulties, I can't authenticate. I believe that the link should be changed, however, I do not know how to proceed. Would you help me? I thank you


![](https://user-images.githubusercontent.com/40409510/219691756-3c6e4122-68be-424b-aab4-fafb59f4c3bd.png)

**Comment by ademircan** [comment]
> > I work in Australia but we also use jp domain. This worked for me.
> > ```
> > routes = {
> >         "GetOffers": "https://flex-capacity-jp.amazon.com/GetOffersForProviderPost",
> >         "AcceptOffer": "https://flex-capacity-jp.amazon.com/AcceptOffer",
> >         "GetAuthToken": "https://api.amazon.com/auth/register",
> >         "ForfeitOffer": "https://flex-capacity-jp.amazon.com/schedule/blocks/",
> >         "GetEligibleServiceAreas": "https://flex-capacity-jp.amazon.com/eligibleServiceAreas",
> >         "GetOfferFiltersOptions": "https://flex-capacity-jp.amazon.com/getOfferFiltersOptions"
> >     }
> > ```
> 
> thank you very much. I'm still having difficulties, I can't authenticate. I believe that the link should be changed, however, I do not know how to proceed. Would you help me? I thank you
> 
> ![](https://user-images.githubusercontent.com/40409510/219691756-3c6e4122-68be-424b-aab4-fafb59f4c3bd.png)

You need to copy the link and it will redirect you to Amazon webpage. Once you logged in, Once you have logged in, simply copy and paste the link into the terminal.

**Comment by dymmyttry** [comment]
> I did this procedure. But when I click on the link I am redirected to amazon.com and with that I cannot log in, because my account is amazon japan.

**Comment by ademircan** [comment]
Why can't you login? Could you please share more information? You should be fine if you changed the routes

**Comment by dymmyttry** [comment]
> Why can't you login? Could you please share more information? You should be fine if you changed the routes

I made the changes to the routes. But when I start the application, it asks me to click on the link and I am directed to amazon.com. So I can't complete the login so I can copy the url and paste.

I believe this link that I colored red needs to be changed.

![1](https://user-images.githubusercontent.com/40409510/219843453-c8821e27-3745-410a-b939-ae3a1aca161f.png)
![2](https://user-images.githubusercontent.com/40409510/219843454-378583ae-7181-4904-a3c6-33a0ec1214af.png)

**Comment by ademircan** [comment]
This looks fine. All you need to do is proceed to sign in and you will come up with something like an error. Once you see that, copy the link and paste into the terminal.

That link contains the access token of your account. Once you successfully done this process, you do not have to sign in each time when you run the app.

**Comment by dymmyttry** [comment]
> This looks fine. All you need to do is proceed to sign in and you will come up with something like an error. Once you see that, copy the link and paste into the terminal.
> 
> That link contains the access token of your account. Once you successfully done this process, you do not have to sign in each time when you run the app.

yes, I already did this process with third party sites and it worked, however I was directed to amazon.co.jp I logged in and then copied and pasted the error url and it worked. In this case here, I can't login because it's on amazon.com

**Comment by ademircan** [comment]
What's the webpage looks like when you logged in?

I am also in jp region and this app redirects me to amazon.com page too and I am able to login without having any problem.

**Comment by dymmyttry** [comment]
> this error message appears. Could you share your settings?

![image](https://user-images.githubusercontent.com/40409510/219843901-4a9c2490-c4ef-4799-a78f-d74cc65ec7f2.png)

**Comment by dymmyttry** [comment]
> What's the webpage looks like when you logged in?
> 
> I am also in jp region and this app redirects me to amazon.com page too and I am able to login without having any problem.


I tried using the amazon.co.jp link and was successfully redirected. I logged in, copied the url and pasted it. A different error occurred.

![image](https://user-images.githubusercontent.com/40409510/219844011-01fc5d6e-bf37-4049-8628-7589be3327d9.png)

**Comment by ademircan** [comment]
Exactly same settings, not much to change. It seems like you are missing this route. Could you add and try it again? 
`"RequestNewAccessToken": "https://api.amazon.com/auth/token",`

And I recommend you to delete the last screenshot because it has your account details.

**Comment by dymmyttry** [comment]
> "RequestNewAccessToken": "https://api.amazon.com/auth/token",

added the route. This error appears

![image](https://user-images.githubusercontent.com/40409510/219844341-c7eb1ecc-f684-42ae-a38f-de910aec3c1f.png)

**Comment by ademircan** [comment]
Could you please try via your code editor's terminal?

**Comment by dymmyttry** [comment]
> Could you please try via your code editor's terminal?

I did the test as you asked, it didn't work either

![image](https://user-images.githubusercontent.com/40409510/219852514-e4ae7910-56c5-4ef4-b361-3185a0ae6a15.png)

**Comment by ademircan** [comment]
I realised you changed the link variable from amazon.com to amazon.co.jp. It has to be amazon.com, keep the original one. You only need to change the routes to jp

**Comment by dymmyttry** [comment]
> I realised you changed the link variable from amazon.com to amazon.co.jp. It has to be amazon.com, keep the original one. You only need to change the routes to jp

unfortunately with amazon.com nothing works. I'll try to see other ways. Thanks a lot for the help

![image](https://user-images.githubusercontent.com/40409510/219853400-8a916723-795d-40ba-a4f3-f2a4141425a1.png)

**Comment by dymmyttry** [comment]
> Could you please try via your code editor's terminal?

could you tell me which program you are using?

**Comment by ademircan** [comment]
> 
vs code but I reckon there's nothing related with the code editor

**Comment by dymmyttry** [comment]
> > 
> 
> vs code but I reckon there's nothing related with the code editor

Got it, I don't know what it could be anymore :(

**Comment by ssmusic19** [comment]
@dymmyttry https://www.amazon.co.jp/ap/signin?ie=UTF8&clientContext=134-9172090-0857541&openid.pape.max_auth_age=0&use_global_authentication=false&accountStatusPolicy=P1&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&use_audio_captcha=false&arb=97b4a0fe-13b8-45fd-b405-ae94b0fec45b&openid.return_to=https%3A%2F%2Fwww.amazon.co.jp%2Fap%2Fmaplanding&openid.assoc_handle=amzn_device_ios_jp&pageId=amzn_device_ios_light&openid.oa2.response_type=token&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&disableLoginPrepopulate=0&openid.oa2.client_id=device%3A32663430323338643639356262653236326265346136356131376439616135392341314d50534c4643374c3541464b&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
This should work with this script.

**Comment by dymmyttry** [comment]
> @dymmyttry https://www.amazon.co.jp/ap/signin?ie=UTF8&clientContext=134-9172090-0857541&openid.pape.max_auth_age=0&use_global_authentication=false&accountStatusPolicy=P1&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&use_audio_captcha=false&arb=97b4a0fe-13b8-45fd-b405-ae94b0fec45b&openid.return_to=https%3A%2F%2Fwww.amazon.co.jp%2Fap%2Fmaplanding&openid.assoc_handle=amzn_device_ios_jp&pageId=amzn_device_ios_light&openid.oa2.response_type=token&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&disableLoginPrepopulate=0&openid.oa2.client_id=device%3A32663430323338643639356262653236326265346136356131376439616135392341314d50534c4643374c3541464b&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0 This should work with this script.

It worked. Thank you very much 👍 :)
