### ISSUE TITLE
Warehouse ID's

### ISSUE THREAD

**Issue by Qasimbaig** [mdesilva/AmazonFlexUnlimited#6]
Can you please give us the ID's of UK warehouses?

**Comment by Qasimbaig** [comment]
Also is this program still working or patched by Amazon?

**Comment by mdesilva** [comment]
I don't have any reason to believe that the program is not working. As for the ids of UK warehouses, you'll have to find those yourself by spying on the network requests made by the Amazon Flex app using something like Charles Proxy.
