### ISSUE TITLE
requests.exceptions.JSONDecodeError: Extra data: line 1 column 5 (char 4)

### ISSUE THREAD

**Issue by j-abellera** [mdesilva/AmazonFlexUnlimited#74]
Does this mean it catches more than one offer and crashes? 

Traceback (most recent call last):
  File "C:\Users\xxxx\AmazonFlexUnlimited\app.py", line 15, in <module>
    flexUnlimited.run()
  File "C:\Users\xxxx\AmazonFlexUnlimited\lib\FlexUnlimited.py", line 470, in run
    Log.error(offersResponse.json())
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 5 (char 4)

**Comment by MY20-PHEV** [comment]
I think it means that the offer reponse object was not valid JSON. Check your routes and warehouse_id's for typos

**Comment by j-abellera** [comment]
> requests.exceptions.JSONDecodeError: Extra data:

requests.exceptions.JSONDecodeError: Extra data
Only happens sometimes. caused by two records in json returned. I'm not adept in python to fix this myself.

**Comment by Brububabu111** [comment]
> I think it means that the offer reponse object was not valid JSON. Check your routes and warehouse_id's for typos

hello are you able to help me fixing the code on my Mac?

**Comment by Brububabu111** [comment]
> > requests.exceptions.JSONDecodeError: Extra data:
> 
> requests.exceptions.JSONDecodeError: Extra data Only happens sometimes. caused by two records in json returned. I'm not adept in python to fix this myself.

Hello would you be able to help me on a bug for this code? 

Thanks

**Comment by ssmusic19** [comment]
@j-abellera sometimes amazon's get-offers requests return error code 500 with a bunch of html instead of json. You can add a check like this towards the end of the script when it checks the error codes:
elif offersResponse.status_code >= 500:
    Log.error("code 500 error")
    continue

**Comment by j-abellera** [comment]
@ssmusic19 My workaround was to just remove the break from the else. Your solution seems like a more correct fix. Thanks for the input.
