### ISSUE TITLE
request attempt 0

### ISSUE THREAD

**Issue by jddms2** [mdesilva/AmazonFlexUnlimited#83]
when I run script this is the message I get " starting job search ... 0 request attempts" Is this supposed to be 0 ???

**Comment by kyleanderson84** [comment]
Yes, it's counting searches, it'll display the count every 50 I believe, I changed the code to mine to do every 10 though. Good luck

**Comment by jddms2** [comment]
I looked in json and under retrylimit: 10. shouldn't it show "request attempts 10" ??

**Comment by kyleanderson84** [comment]
The original code only displays every 50 counts, so 10 retries won't show, try 100 or 200. Also it won't display the last 50 because of how the code is written, the search terminates before it triggers the bit of code that displays the count

**Comment by jddms2** [comment]
I have one more question. Is there a limit on attempts before it flags Amazon?? Sent from Mail for Windows From: Kyle AndersonSent: Friday, March 3, 2023 3:27 PMTo: mdesilva/AmazonFlexUnlimitedCc: jddms2; AuthorSubject: Re: [mdesilva/AmazonFlexUnlimited] request attempt 0 (Issue #83) The original code only displays every 50 counts, so 10 retries won't show, try 100 or 200. Also it won't display the last 50 because of how the code is written, the search terminates before it triggers the bit of code that displays the count—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by kyleanderson84** [comment]
Nobody really knows a definite number that triggers it, in the Flex Driver App it says something along the lines of, "You've been clicking too fast for too long" or something, so speed is more the issue, at 1.2 or 1.3 seconds got can usually let it run a half hour before the Amazon services temporarily stop responding to you. I've also heard of people doing 10 seconds and letting it run all the time. It's kinda just trial and error, just avoid triggering Amazon servers blocking you, you don't want to get flagged as a bot user. :)

**Comment by jddms2** [comment]
Thank you 😁
