### ISSUE TITLE
Running App and Script

### ISSUE THREAD

**Issue by jddms2** [mdesilva/AmazonFlexUnlimited#84]
can you use the phone app and run the script at the same time ??

**Comment by vsrromero** [comment]
I believe yes, didn’t test at this app yet but you can in other apps, that I believe work on same way, but be aware, if you set this app to grab a block and at the same time click in refresh button at amazon flex app, you will get the “you clicked too long/too many times” message twice faster.

**Comment by Hrasseee** [comment]
Decrease the number of clicks
