### ISSUE TITLE
App quits all of a Sudden

### ISSUE THREAD

**Issue by beewax** [mdesilva/AmazonFlexUnlimited#95]
Hi, 

I'm new here and don't know much about coding. After new windows update the apps suddenly quits when using it (it was working fine for a while. I tried running from the same folder as my python install and also adding the input () parameter, but I got an error right away. 

Any help is appreciated.

**Comment by mdesilva** [comment]
Please paste a copy of the error message.

**Comment by beewax** [comment]
Thank you so much for asking. It started to work after I updated the libraries or at least I think, that helped. Thanks again.
