### ISSUE TITLE
INFO: Rate limit reached. 

### ISSUE THREAD

**Issue by rgribeiro2009** [mdesilva/AmazonFlexUnlimited#99]
**Welcome to Flexxer Deals*** 

INFO: Starting job search...
6052006290:AAEvabsW2LWy3_VpeFobDY3EtWQ33IrsIgQ / -87xxxxxxxxx/ 🐇🔍 Searching for blocks
0 requests attempted

INFO: Rate limit reached. Waiting for 30 minutes.
6052006290:AAEvabsW2LWy3_VpeFobDY3EtWQ33IrsIgQ / -87xxxxxxxx / ⏱️ Rate limit reached. Waiting for 30 minutes.   

This error appears immediately after I run the script.

**Comment by rgribeiro2009** [comment]
when I press play on the script, the code 400 already appears

**Comment by Hrasseee** [comment]
It happened to me once, I installed it again and got the code generated on the Amz page

**Comment by rgribeiro2009** [comment]
I didn't understand when you talk about Amazon page.  my script was working normally, I didn't change anything and this message started to appear

**Comment by Hrasseee** [comment]
I'm not an expert,but try to save the token in the config.json file when you install again

**Comment by rgribeiro2009** [comment]
> I'm not an expert,but try to save the token in the config.json file when you install again

it worked perfectly! Thanks

**Comment by sack2116** [comment]
> > I'm not an expert,but try to save the token in the config.json file when you install again
> 
> it worked perfectly! Thanks

how do you re-save your token in the config file?
